// HrFlow profile (kept for backward compat with existing API routes)
export interface HrFlowProfile {
  key: string;
  reference: string | null;
  source_key: string;
  info: {
    full_name: string;
    first_name: string;
    last_name: string;
    email: string;
    phone: string | null;
    location: { text: string | null } | null;
    summary: string | null;
    picture: string | null;
  };
  experiences: HrFlowExperience[];
  educations: HrFlowEducation[];
  skills: HrFlowEntityItem[];
  languages: HrFlowEntityItem[];
  tags: { name: string; value: string }[];
  created_at: string;
  updated_at: string;
}

export interface HrFlowExperience {
  title: string | null;
  company: string | null;
  location: { text: string | null } | null;
  date_start: { iso8601: string | null } | null;
  date_end: { iso8601: string | null } | null;
  description: string | null;
}

export interface HrFlowEducation {
  title: string | null;
  school: string | null;
  location: { text: string | null } | null;
  date_start: { iso8601: string | null } | null;
  date_end: { iso8601: string | null } | null;
  description: string | null;
}

export interface HrFlowEntityItem {
  name: string;
  type: string | null;
  value: string | null;
}

// ─── New: Web-sourced profiles ─────────────────────────────────

export type SourceType = "github" | "linkedin" | "reddit" | "internet" | "indeed" | "hellowork";

export interface ProfileSource {
  type: SourceType;
  url: string;
  label: string; // e.g. "github.com/username"
}

export interface ReconstructedExperience {
  title: string;
  company: string;
  location: string;
  period: string; // e.g. "2020 - 2023"
  description: string;
}

export interface ReconstructedEducation {
  degree: string;
  school: string;
  period: string;
}

export interface SourcedProfile {
  key: string;                         // uuid
  name: string;
  title: string;
  location: string;
  experience_years: number;
  summary: string;                     // AI-generated by OpenClaw
  sources: ProfileSource[];
  skills: string[];
  experiences: ReconstructedExperience[];
  educations: ReconstructedEducation[];
  hrflow_score: number;                // 0-100, -1 = not yet scored
  hrflow_key: string | null;           // null until indexed by HrFlow
  avatar_color: string;                // hex, pre-computed by OpenClaw
}

// ─── Feed logs (sourcing pipeline) ─────────────────────────────

export interface FeedLog {
  id: string;
  source: "github" | "linkedin" | "reddit" | "internet";
  message: string;
  type: "info" | "found" | "score" | "done";
}

// ─── Feed + Chat (unchanged) ────────────────────────────────────

export interface FeedEvent {
  id: string;
  time: string;
  action: string;
  detail: string;
  status: "done" | "running" | "error";
  type: "connect" | "parse" | "score" | "source" | "analyze" | "notify";
}

export interface ChatMessage {
  id: string;
  type: "user" | "agent";
  text: string;
  time: string;
}

// ─── Account / Supabase types ───────────────────────────────────

export interface SavedSearch {
  id: string;
  session_id: string;
  query: string;
  profile_count: number;
  created_at: string;
  results?: SourcedProfile[];
}

export interface ShortlistEntry {
  id: string;
  session_id: string;
  profile_key: string;
  profile_data: SourcedProfile;
  pipeline_stage?: string;
  saved_at: string;
}

export interface OutreachEntry {
  id: string;
  session_id: string;
  profile_key: string;
  profile_name: string;
  message: string;
  created_at: string;
}
